version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage/app/public:ro
    ports:
      - "8000:8000"
    depends_on:
      - node
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:qsnoEkb6xxrkq6guRObFceWSRCIsNGGFHpxtFZvP/MA=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=8000

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - .:/var/www/html
    command: tail -f /dev/null # Keep the container running

  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/var/lib/sqlite3
    ports:
      - "5432:5432" #expose port to allow external tools to connect. Remove if not needed.